### ISSUE TITLE
Improve the design of button on create memory form 

### ISSUE THREAD

**Issue by luckykumarirai** [Tejas1510/Athavani#41] opened 2021-01-02 12:14 UTC
# Improve the alignment of submit button and clear button on create memory form
![issue1](https://user-images.githubusercontent.com/59636719/103457086-203c9480-4d22-11eb-976d-7695804b4367.jpg)

**Comment by Tejas1510** [comment] 2021-01-02 13:52
Thanks for the PR
@luckykumarirai you can't make a PR unless the issue is Assigned to you
Also, we want the button to be placed one below the other
So I am closing the pull request

**Closed by Tejas1510** 2021-01-02 13:52 UTC
