### ISSUE TITLE
Zoom Out Effect on Hovering

### ISSUE THREAD

**Issue by anushka-srivastava22** [Tejas1510/Athavani#296] opened 2021-06-11 16:38 UTC
**Is your feature request related to a problem? Please describe.**
The cards of team members are static , it would be good to add hovering effects on them.

**Describe the solution you'd like**
 I can add zoom out effect on hovering on the cards with box shadow .

**Comment by AmeyaJain-25** [comment] 2021-06-11 17:11
> **Is your feature request related to a problem? Please describe.**
> The cards of team members are static , it would be good to add hovering effects on them.
> 
> **Describe the solution you'd like**
> I can add zoom out effect on hovering on the cards with box shadow .

@anushka-srivastava22  Can you add some screenshots or describe a bit more about cards on which page, etc.

**Comment by AmeyaJain-25** [comment] 2021-06-14 18:47
@anushka-srivastava22 , Can you give any update or let us know more about the issue?

Otherwise if the issue isn't as such, then we can close this one and you can try for some other fresh one's.

**Closed** 2021-06-16 08:25 UTC
