### ISSUE TITLE
Shows Web-app without Login

### ISSUE THREAD

**Issue by ashishnagpal2498** [Tejas1510/Athavani#227] opened 2021-05-17 17:49 UTC
**Describe the bug**
All the posts are viewed for like 2-3 secs. 

**To Reproduce**
1. Go to project URL.
2. Click on back button of browser. Twice or thrice.
3. See error. (screenshot 1)
4. After it gets redirected to signIn page with token error. ( screenshot 2)

**Expected behavior**
Shouldn't be able to see the content.

**Screenshots**
![newIssue2](https://user-images.githubusercontent.com/36301481/118533639-f088a900-b765-11eb-8892-1d40cc949768.png)
![newIssue1](https://user-images.githubusercontent.com/36301481/118533662-f54d5d00-b765-11eb-81a4-fdc2f94c5321.png)

**Comment by AmeyaJain-25** [comment] 2021-05-19 19:09
I would like to work on this issue @ashishnagpal2498 .
Assign me.


Also, I have some questions.

I'm trying to reproduced this issue. Cannot produce it. @ashishnagpal2498 
If the user is once logged in, then if he/she tries to come to signin page, then it redirects it to home/dashboard page.

And, the user token expired occurs if the you are signed in and the localhost backend server is disconnected or terminated. Then the user logs out and can see this error message for multiple times.

**Comment by AmeyaJain-25** [comment] 2021-05-20 15:28
Yes @sanjay270899 , got the issue.
I debugged it. It's happening because on signup page, there is an check written if an authenticated user goes to that page, then he/she shouldn't be allowed.
The code is as follows:
![code](https://user-images.githubusercontent.com/66305085/119006100-af82d580-b9ad-11eb-8e6f-015cbc67d9e9.png)

Here I have 2 solutions.
1. We can make the whole page background to be blur and show a loader when signin process goes on, so that no one can click on signup. 
2. The way you said that we can disable the signup button or link.

I would like to work on this. I can solve this. Please assign this issue to me. Also please let me know that which method should I go with. 1 or 2

**Comment by ashishnagpal2498** [comment] 2021-05-21 06:19
I guess that's the other issue. @sanjay270899 .
In this one you should be completely logged out from app first. 
Now open this link - "athavani-sanjay-frontend.netlify.app/"
Press "back" button of your browser multiple times until you see the contents of the web-app for 5 secs. And then it gets redirected to SignIn page with "Token Error"

**Comment by AmeyaJain-25** [comment] 2021-05-21 17:00
Yes, I got the issue @ashishnagpal2498.
This is happening because if we go back, then user is going to the home page, then after the page renders, the check is done (Reference: Image provided above snippet) whether user is already logged in or not.
This issue can be resolved by checking it before the page launches.

I have an Idea of making a Private Routes Component which can do the checking before mounting the Components.

Please assign it to me @ashishnagpal2498 and @sanjay270899 . I can solve this.

**Closed** 2021-05-29 10:24 UTC
Labels: GSSOC21, Level3, bug
